export type View = 'Dashboard' | 'Products' | 'Billing' | 'Analytics' | 'Khata';
export type Theme = 'light' | 'dark';

export type ContactType = 'customer' | 'supplier';
export type EntryType = 'credit_given' | 'payment_received';

export interface Contact {
    id: string;
    user_id: string;
    name: string;
    phone_number?: string;
    contact_type: ContactType;
    current_balance: number;
    created_at: Date;
}

export interface LedgerEntry {
    id: string;
    contact_id: string;
    user_id: string;
    amount: number;
    entry_type: EntryType;
    description?: string;
    transaction_date: Date;
}

export interface Product {
  sku: string;
  user_id: string;
  name: string;
  costPrice: number;
  price: number;
  quantity: number;
  lowStockThreshold: number;
}

export interface CartItem {
  productSku: string;
  name: string;
  price: number;
  quantity: number;
}

// Represents an item within a completed transaction
export interface TransactionItem {
  productSku: string;
  name: string; // Denormalized for easier receipt rendering
  quantitySold: number;
  pricePerItem: number; // Price at the time of sale
}

export interface Transaction {
  id?: number; // Optional because it's generated by the database
  user_id: string;
  timestamp: Date;
  items: TransactionItem[];
  subtotal: number;
  discountPercent: number;
  discountRs?: number; // Optional: Fixed rupee discount
  total: number;
  contact_id?: string; // Optional: If the transaction is linked to a contact (for Khata)
  isKhataTransaction?: boolean; // Optional: To identify if this was added to Khata
}