-- ========= SCHEMA AND TABLES =========

-- Ensure the 'public' schema exists.
CREATE SCHEMA IF NOT EXISTS public;

-- 1. PRODUCTS TABLE
-- Stores all inventory items.
CREATE TABLE public.products (
    sku TEXT PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    name TEXT NOT NULL,
    cost_price NUMERIC NOT NULL CHECK (cost_price >= 0),
    price NUMERIC NOT NULL CHECK (price >= 0),
    quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    low_stock_threshold INTEGER NOT NULL DEFAULT 10 CHECK (low_stock_threshold >= 0),
    expiry_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now() -- Corrected type
);
COMMENT ON TABLE public.products IS 'Stores product inventory information.';

-- 2. CONTACTS TABLE
-- Stores customer and supplier details for Khata management.
CREATE TABLE public.contacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth.users(id),
    name TEXT NOT NULL,
    phone_number TEXT,
    contact_type TEXT NOT NULL CHECK (contact_type IN ('customer', 'supplier')),
    current_balance NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now() -- Corrected type
);
COMMENT ON TABLE public.contacts IS 'Stores customer and supplier contact information for the ledger.';

-- 3. TRANSACTIONS TABLE
-- Records each sale.
CREATE TABLE public.transactions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(), -- Corrected type and quoted name
    subtotal NUMERIC NOT NULL CHECK (subtotal >= 0),
    discount_percent NUMERIC NOT NULL DEFAULT 0 CHECK (discount_percent >= 0 AND discount_percent <= 100),
    total NUMERIC NOT NULL CHECK (total >= 0),
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.transactions IS 'Records header information for each sale.';

-- 4. TRANSACTION_ITEMS TABLE
-- A junction table detailing the products within each transaction.
CREATE TABLE public.transaction_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_id BIGINT NOT NULL REFERENCES public.transactions(id) ON DELETE CASCADE,
    product_sku TEXT NOT NULL REFERENCES public.products(sku) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    quantity_sold INTEGER NOT NULL CHECK (quantity_sold > 0),
    price_per_item NUMERIC NOT NULL CHECK (price_per_item >= 0)
);
COMMENT ON TABLE public.transaction_items IS 'Stores individual line items for each transaction.';

-- 5. LEDGER_ENTRIES TABLE
-- Tracks credits and payments for each contact in the Khata.
CREATE TABLE public.ledger_entries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contact_id UUID NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    entry_type TEXT NOT NULL CHECK (entry_type IN ('credit_given', 'payment_received')),
    description TEXT,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT now() -- Corrected type
);
COMMENT ON TABLE public.ledger_entries IS 'Records individual credit/debit entries for contacts.';


-- ========= ENABLE ROW LEVEL SECURITY (RLS) =========
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledger_entries ENABLE ROW LEVEL SECURITY;


-- ========= CREATE RLS POLICIES =========

CREATE POLICY "Users can manage their own products" ON public.products
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can manage their own contacts" ON public.contacts
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can manage their own transactions" ON public.transactions
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can manage items in their own transactions" ON public.transaction_items
    FOR ALL USING ( (SELECT user_id FROM public.transactions WHERE id = transaction_id) = auth.uid() );

CREATE POLICY "Users can manage ledger entries for their own contacts" ON public.ledger_entries
    FOR ALL USING ( (SELECT user_id FROM public.contacts WHERE id = contact_id) = auth.uid() );


-- ========= AUTOMATION FOR KHATA BALANCE =========

CREATE OR REPLACE FUNCTION public.update_contact_balance()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    IF NEW.entry_type = 'credit_given' THEN
        UPDATE public.contacts
        SET current_balance = current_balance + NEW.amount
        WHERE id = NEW.contact_id;
    ELSIF NEW.entry_type = 'payment_received' THEN
        UPDATE public.contacts
        SET current_balance = current_balance - NEW.amount
        WHERE id = NEW.contact_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_ledger_entry_insert
AFTER INSERT ON public.ledger_entries
FOR EACH ROW EXECUTE FUNCTION public.update_contact_balance();

COMMENT ON TRIGGER on_ledger_entry_insert ON public.ledger_entries IS 'Updates the current_balance in the contacts table after a new ledger entry is created.';